# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: joepolny@gmail.com
author_name: Joe Polny
ide_jetbrains: false
ide_vscode: true
preset_name: custom
project_name: demo
use_daisy_ui: true
use_eslint_prettier: true
use_github_actions: false
use_jest: true
use_playwright: true
use_tailwind: true

